schema_version = 1
name = "bananasplit"
version = "0.1.0"

cells = [
    "../../pulp-engines/coordination-state-sqlite-cell/pulp.cell.toml",
    "../../pulp-engines/http-json-cell/pulp.cell.toml",
    "../api-cell/pulp.cell.toml",
    "lua-orchestrator.cell.toml",
]

[orchestrator]
manifest = "lua-orchestrator.cell.toml"
script = "bananasplit.lua"
sha256 = "e9a023f5f60de9f0fc93f80a79b0615242ddfe1b929dbb721d67efe24f76f050"
