schema_version = 1
name = "bananasplit"
version = "0.1.0"

cells = [
    "../../pulp-engines/coordination-state-sqlite-cell/pulp.cell.toml",
    "../../pulp-engines/http-json-cell/pulp.cell.toml",
    "../api-cell/pulp.cell.toml",
    "lua-orchestrator.cell.toml",
]

[orchestrator]
manifest = "lua-orchestrator.cell.toml"
script = "bananasplit.lua"
sha256 = "ea9a8cdde6e1fca75547a603aea53893cd39011edbe86224ee1b8f366e9cb70b"
